{
    config,
    lib,
    pkgs,
    ...
}:
{
    lesbos.secrets.system = {
        "downloaders/gluetun.env".mode = "0444";
        "downloaders/slskd.env".mode = "0444";
    };

    # Runtime
    virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
        let
            matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
        in
        {
            "${matchAll}".allowedUDPPorts = [ 53 ];
        };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."deluge" = {
        image = "lscr.io/linuxserver/deluge:latest";
        environment = {
            "DELUGE_LOGLEVEL" = "info";
            "PGID" = "0";
            "PUID" = "0";
            "TZ" = "America/New_York";
        };
        volumes = [
            "/media-support/downloads/downloads:/downloads:rw"
            "/media-support/downloads/torrents:/torrents:rw"
            "/media-support/services/downloaders/deluge:/config:rw"
            "/media-support/services/downloaders/gluetun:/gluetun-shared:rw"
        ];
        dependsOn = [
            "gluetun"
        ];
        log-driver = "journald";
        extraOptions = [
            "--network=container:gluetun"
        ];
    };
    systemd.services."podman-deluge" = {
        serviceConfig = {
            Restart = lib.mkOverride 90 "always";
        };
        partOf = [
            "podman-compose-downloaders-root.target"
        ];
        wantedBy = [
            "podman-compose-downloaders-root.target"
        ];
    };
    virtualisation.oci-containers.containers."gluetun" = {
        image = "qmcgaw/gluetun";
        environmentFiles = [
            config.sops.secrets."downloaders/gluetun.env".path
        ];
        volumes = [
            "/media-support/services/downloaders/gluetun:/gluetun-shared:rw"
        ];
        ports = [
            "8112:8112/tcp"
            "8000:8000/tcp"
            "5030:5030/tcp"
        ];
        labels = {
            "compose2nix.settings.sops.secrets" = "downloaders/gluetun.env";
        };
        log-driver = "journald";
        extraOptions = [
            "--cap-add=NET_ADMIN"
            "--device=/dev/net/tun:/dev/net/tun:rwm"
            "--network-alias=gluetun"
            "--network=downloaders_default"
        ];
    };
    systemd.services."podman-gluetun" = {
        serviceConfig = {
            Restart = lib.mkOverride 90 "always";
        };
        after = [
            "podman-network-downloaders_default.service"
        ];
        requires = [
            "podman-network-downloaders_default.service"
        ];
        partOf = [
            "podman-compose-downloaders-root.target"
        ];
        wantedBy = [
            "podman-compose-downloaders-root.target"
        ];
    };
    virtualisation.oci-containers.containers."slskd" = {
        image = "slskd/slskd:latest";
        environmentFiles = [
            config.sops.secrets."downloaders/slskd.env".path
        ];
        volumes = [
            "/media-support/downloads/downloads:/downloads:rw"
            "/media-support/media:/media:rw"
            "/media-support/services/downloaders/gluetun:/gluetun-shared:rw"
            "/media-support/services/downloaders/slskd:/config:rw"
        ];
        labels = {
            "compose2nix.settings.sops.secrets" = "downloaders/slskd.env";
        };
        dependsOn = [
            "gluetun"
        ];
        log-driver = "journald";
        extraOptions = [
            "--network=container:gluetun"
        ];
    };
    systemd.services."podman-slskd" = {
        serviceConfig = {
            Restart = lib.mkOverride 90 "always";
        };
        partOf = [
            "podman-compose-downloaders-root.target"
        ];
        wantedBy = [
            "podman-compose-downloaders-root.target"
        ];
    };

    # Networks
    systemd.services."podman-network-downloaders_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStop = "podman network rm -f downloaders_default";
        };
        script = ''
            podman network inspect downloaders_default || podman network create downloaders_default
        '';
        partOf = [ "podman-compose-downloaders-root.target" ];
        wantedBy = [ "podman-compose-downloaders-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-downloaders-root" = {
        unitConfig = {
            Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
    };
}
