keys:
    - &root age177zdzvkyya5lzm0xfet99etw09347wggaqqkxf7ys8qq2aguyghs8glvtn
    - &homelab-host-router age12689ppzdxx3mpe30798842f2cuaeps2z4mz5ep48k8rd2za5msmsus5pw7
    # @add:key-def

creation_rules:
  - path_regex: secrets/global.yaml$
    key_groups:
      - age:
          - *root
          - *homelab-host-router
          # @add:key-ref
  - path_regex: secrets/homelab/global.yaml$
    key_groups:
      - age:
          - *root
          - *homelab-host-router
          # @add:homelab:key-ref
  - path_regex: secrets/personal/global.yaml$
    key_groups:
      - age:
          - *root
          # @add:personal:key-ref
  - path_regex: secrets/homelab/per-system/router/system.yaml$
    key_groups:
      - age:
          - *root
          - *homelab-host-router
  # @add:new-path