keys:
    - &root age177zdzvkyya5lzm0xfet99etw09347wggaqqkxf7ys8qq2aguyghs8glvtn
    - &homelab-host-router age17nvtsmujuxq3pr9yrx9p4k6xkfq8zm4tr65luczgdt6wtyq3g9js9p7pul
    # @add:key-def

creation_rules:
  - path_regex: secrets/global.yaml$
    key_groups:
      - age:
          - *root
          - *homelab-host-router
          # @add:key-ref
  - path_regex: secrets/homelab/global.yaml$
    key_groups:
      - age:
          - *root
          - *homelab-host-router
          # @add:homelab:key-ref
  - path_regex: secrets/personal/global.yaml$
    key_groups:
      - age:
          - *root
          # @add:personal:key-ref
  - path_regex: secrets/homelab/per-system/router/system.yaml$
    key_groups:
      - age:
          - *root
          - *homelab-host-router
  # @add:new-path