# Auto-generated by compose2nix.

{
    pkgs,
    lib,
    config,
    ...
}:
let
    pl = path: config.sops.placeholder."osync/${path}";
in

{
    # Runtime
    virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
        let
            matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
        in
        {
            "${matchAll}".allowedUDPPorts = [ 53 ];
        };

    lesbos.secrets.system = {
        "osync/postgres/password" = { };
        "osync/s3/access_key" = { };
        "osync/s3/secret_key" = { };
        "osync/s3/kms_secret" = { };
        "osync/auth/better_auth" = { };
        "osync/auth/sync" = { };
    };
    sops.templates."osync.env" = {
        mode = "0444";
        content = ''
            # ── PostgreSQL ────────────────────────────────────────────────
            POSTGRES_USER=osync
            POSTGRES_PASSWORD=${pl "postgres/password"}
            POSTGRES_DB=osync
            DATABASE_URL=postgresql://osync:${pl "postgres/password"}@postgres:5432/osync    

            # ── MinIO (S3-compatible storage) ────────────────────────────
            S3_ACCESS_KEY=${pl "s3/access_key"}
            S3_SECRET_KEY=${pl "s3/secret_key"}
            S3_BUCKET=osync-bucket
            S3_REGION=us-east-1
            S3_ENDPOINT=http://minio:9000

            # MinIO server-side encryption key
            # Format: name:base64(32 random bytes)
            # Generate: echo "osync-key:$(openssl rand -base64 32)"
            MINIO_KMS_SECRET_KEY=osync-key:${pl "s3/kms_secret"}
            MINIO_PUBLIC_URL=https://s3.osync.dax.gay
            MINIO_ROOT_USER=${pl "s3/access_key"}
            MINIO_ROOT_PASSWORD=${pl "s3/secret_key"}
            MINIO_SKIP_CHOWN=true
            MINIO_KMS_AUTO_ENCRYPTION=on
            MINIO_ADDRESS = 0.0.0.0:9000
            MINIO_CONSOLE_ADDRESS = 0.0.0.0:9001
            MINIO_HEALTHCHECK_CODE = 200
            MINIO_HEALTHCHECK_URL = http://0.0.0.0:9000/minio/health/live

            # ── Auth ──────────────────────────────────────────────────────
            # Generate: openssl rand -hex 32
            BETTER_AUTH_SECRET=${pl "auth/better_auth"}
            SYNC_TOKEN_SECRET=${pl "auth/sync"}

            # ── App ───────────────────────────────────────────────────────
            PORT=3000

            # UI language: en (default) or ko
            LANGUAGE=en

            # Image tag. Leave as-is for normal CPUs. If your CPU lacks AVX2 (e.g. Intel
            # Celeron/Pentium) and the api container crashes with "Illegal instruction
            # (core dumped)", use the baseline build: IMAGE_TAG=latest-baseline
            IMAGE_TAG=latest
            PUBLIC_URL=https://osync.dax.gay
            CORS_ORIGIN=https://osync.dax.gay
            SELF_HOSTED=true
            SYNC_TOKEN_TTL_SECONDS=120
            COORDINATOR_DATA_DIR=/data/coordinators        
        '';
    };

    # Containers
    virtualisation.oci-containers.containers."osync-api" = {
        image = "thomasjeong/osync:latest";
        environmentFiles = [ config.sops.templates."osync.env".path ];
        volumes = [
            "/services/osync/app:/data/coordinators:rw"
        ];
        ports = [
            "0.0.0.0:4500:3000/tcp"
        ];
        dependsOn = [
            "osync-minio"
            "osync-postgres"
        ];
        log-driver = "journald";
        extraOptions = [
            "--network-alias=api"
            "--network=osync_default"
        ];
    };
    systemd.services."podman-osync-api" = {
        serviceConfig = {
            Restart = lib.mkOverride 90 "always";
        };
        after = [
            "podman-network-osync_default.service"
        ];
        requires = [
            "podman-network-osync_default.service"
        ];
        partOf = [
            "podman-compose-osync-root.target"
        ];
        wantedBy = [
            "podman-compose-osync-root.target"
        ];
    };
    virtualisation.oci-containers.containers."osync-minio" = {
        image = "docker.io/webhippie/minio:2025-07-23";
        environmentFiles = [ config.sops.templates."osync.env".path ];
        volumes = [
            "/services/osync/minio:/data:rw"
        ];
        ports = [
            "0.0.0.0:4501:9001/tcp"
        ];
        log-driver = "journald";
        extraOptions = [
            "--health-cmd=[\"curl\", \"-f\", \"http://localhost:9000/minio/health/live\"]"
            "--health-interval=5s"
            "--health-retries=5"
            "--health-timeout=5s"
            "--network-alias=minio"
            "--network=osync_default"
        ];
    };
    systemd.services."podman-osync-minio" = {
        serviceConfig = {
            Restart = lib.mkOverride 90 "always";
        };
        after = [
            "podman-network-osync_default.service"
        ];
        requires = [
            "podman-network-osync_default.service"
        ];
        partOf = [
            "podman-compose-osync-root.target"
        ];
        wantedBy = [
            "podman-compose-osync-root.target"
        ];
    };
    virtualisation.oci-containers.containers."osync-postgres" = {
        image = "postgres:16-alpine";
        environmentFiles = [ config.sops.templates."osync.env".path ];
        volumes = [
            "/services/osync/postgres:/var/lib/postgresql/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
            "--health-cmd=pg_isready -U osync"
            "--health-interval=5s"
            "--health-retries=5"
            "--health-timeout=5s"
            "--network-alias=postgres"
            "--network=osync_default"
        ];
    };
    systemd.services."podman-osync-postgres" = {
        serviceConfig = {
            Restart = lib.mkOverride 90 "always";
        };
        after = [
            "podman-network-osync_default.service"
        ];
        requires = [
            "podman-network-osync_default.service"
        ];
        partOf = [
            "podman-compose-osync-root.target"
        ];
        wantedBy = [
            "podman-compose-osync-root.target"
        ];
    };

    # Networks
    systemd.services."podman-network-osync_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStop = "podman network rm -f osync_default";
        };
        script = ''
            podman network inspect osync_default || podman network create osync_default
        '';
        partOf = [ "podman-compose-osync-root.target" ];
        wantedBy = [ "podman-compose-osync-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-osync-root" = {
        unitConfig = {
            Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
    };
    networking.firewall.allowedTCPPorts = [
        4500
        4501
    ];
}
